include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - 'build/**'

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_use_package_imports: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_dynamic_calls: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    avoid_slow_async_io: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    deprecated_consistency: true
    directives_ordering: true
    eol_at_end_of_file: true
    depend_on_referenced_packages: true
    lines_longer_than_80_chars: true
    literal_only_boolean_expressions: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
