name: tmz_mam_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter # Check for the latest version on pub.dev
  motion_toast: ^2.8.0
  photo_view: ^0.14.0 # Check for the latest version on pub.dev
  http: ^1.1.2
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.1
  data_table_2: ^2.5.10
  dropdown_button2: 2.3.9
  equatable: 2.0.5
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.4.1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^13.1.0
  google_fonts: 6.1.0
  json_path: ^0.7.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.2.2
  sqflite: ^2.3.2
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  url_launcher_android: ^6.2.2
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lints: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/test.jpg
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
