name: tmz_damz
description: "TMZ's digital media asset management system."
publish_to: 'none'
version: 1.2.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.2
  auto_route: ^8.1.3
  bloc: ^8.1.3
  bot_toast: ^4.1.3
  calendar_date_picker2: ^1.0.2
  choice: ^2.3.1
  collection: ^1.18.0
  context_menus: ^2.0.0
  cross_local_storage: ^3.0.0
  dartz: ^0.10.1
  data_table_2: ^2.5.12
  dotted_border: ^2.1.0
  drop_down_search_field: ^1.0.4
  dropdown_button2: 2.3.9
  equatable: ^2.0.5
  extended_image: ^8.2.0
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_dropzone: ^4.0.0
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  logger: ^2.3.0
  material_design_icons_flutter: ^7.0.7296
  overlay_support: ^2.1.0
  package_info_plus: ^8.0.0
  photo_view: ^0.15.0
  provider: ^6.1.2
  radio_group_v2: ^3.1.1
  searchfield: ^1.0.2
  super_tooltip: ^2.0.7
  textfield_tags: ^3.0.1
  timeago: ^3.6.1
  timeago_flutter: ^3.6.0
  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.2
  uuid: ^4.3.3
  web: ^0.5.1
  window_manager: ^0.3.9

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.production
    - .env.staging
    - assets/fonts/
    - assets/images/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


