name: tmz_mam_flutter
description: "TMZ's Photo MAM"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_size_text: 3.0.0
  bloc: ^8.1.3
  bot_toast: ^4.1.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_table_2: ^2.5.10
  dropdown_button2: 2.3.9
  equatable: ^2.0.5
  extended_image: ^8.1.1
  floating_bottom_navigation_bar: 1.5.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_cache_manager: 3.3.1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: 6.1.0
  http: ^1.2.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  json_path: ^0.7.0
  jwt_decoder: ^2.0.1
  material_design_icons_flutter: ^7.0.7296
  mime_type: 1.0.0
  motion_toast: ^2.8.0
  page_transition: 2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  photo_view: ^0.14.0
  provider: ^6.1.1
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  sqflite: ^2.3.2
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.2
  uuid: ^4.3.3
  window_manager: ^0.3.8

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/fonts/
    - assets/images/
    - assets/images/test.jpg
    - assets/lottie_animations/
    - assets/pdfs/
    - assets/rive_animations/
    - assets/videos/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


